// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQFYwZwWjFd1wyljsXrcM53Mp9U9Ax884',
    appId: '1:770486583075:web:cfc1f77c69f5c0bc89d696',
    messagingSenderId: '770486583075',
    projectId: 'recetario-dam-rmy',
    authDomain: 'recetario-dam-rmy.firebaseapp.com',
    storageBucket: 'recetario-dam-rmy.firebasestorage.app',
    measurementId: 'G-NLGXH8YC9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXvZd1gXP_hpAvHlE0771TrqjqItxNSMI',
    appId: '1:770486583075:android:729185f336ef75a389d696',
    messagingSenderId: '770486583075',
    projectId: 'recetario-dam-rmy',
    storageBucket: 'recetario-dam-rmy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_8GAO4mENanc7qfemQ_P4tZ6vPbYvwFk',
    appId: '1:770486583075:ios:6f99f5b62cf287b189d696',
    messagingSenderId: '770486583075',
    projectId: 'recetario-dam-rmy',
    storageBucket: 'recetario-dam-rmy.firebasestorage.app',
    iosBundleId: 'com.recetario.recetarioDamMry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_8GAO4mENanc7qfemQ_P4tZ6vPbYvwFk',
    appId: '1:770486583075:ios:6f99f5b62cf287b189d696',
    messagingSenderId: '770486583075',
    projectId: 'recetario-dam-rmy',
    storageBucket: 'recetario-dam-rmy.firebasestorage.app',
    iosBundleId: 'com.recetario.recetarioDamMry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQFYwZwWjFd1wyljsXrcM53Mp9U9Ax884',
    appId: '1:770486583075:web:05ea6748b793d5b789d696',
    messagingSenderId: '770486583075',
    projectId: 'recetario-dam-rmy',
    authDomain: 'recetario-dam-rmy.firebaseapp.com',
    storageBucket: 'recetario-dam-rmy.firebasestorage.app',
    measurementId: 'G-7570VGSYZK',
  );
}
